version: "3.7"
services:
  flask-admin-nginx:
    container_name: flask-admin-nginx
    image: nginx
    restart: always
    volumes:
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - flask-admin-net
    depends_on:
      - flask-admin
    ports:
      - "80:80"

  flask-admin:
    container_name: flask-admin
    image: flask-admin
    build: .
    networks:
      - flask-admin-net
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    volumes:
      - ./:/flask-admin
    restart: always
    links:
      - mysqldb
    environment:
      - FLASK_APP=project
      - FLASK_ENV=${FLASK_ENV:-development}
      - SQLALCHEMY_DATABASE_URI=${SQLALCHEMY_DATABASE_URI}
    command: ["sh", "./etc/docker-entrypoint.sh"]

  mysqldb:
    container_name: mysqldb
    image: mysql:5.7
    networks:
      - flask-admin-net
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: solodb
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - "3306:3306"
    volumes:
      - solovolume:/var/lib/mysql
    restart: always

networks:
  flask-admin-net:

volumes:
  solovolume:
