"""empty message

Revision ID: 191d14b416fe
Revises: 
Create Date: 2022-05-30 22:15:20.740240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '191d14b416fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(length=10), nullable=False),
    sa.Column('registered_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=10), nullable=False),
    sa.Column('registered_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('path_original', sa.String(length=200), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_damaged', sa.Boolean(), nullable=True),
    sa.Column('conf_score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_original')
    )
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_inferenced', sa.Boolean(), nullable=False),
    sa.Column('inferenced_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('path_inference_dent', sa.String(length=200), nullable=False),
    sa.Column('path_inference_scratch', sa.String(length=200), nullable=False),
    sa.Column('path_inference_spacing', sa.String(length=200), nullable=False),
    sa.Column('is_inspected', sa.Boolean(), nullable=False),
    sa.Column('inspected_on', sa.DateTime(), nullable=True),
    sa.Column('path_inspect_dent', sa.String(length=200), nullable=True),
    sa.Column('path_inspect_scratch', sa.String(length=200), nullable=True),
    sa.Column('path_inspect_spacing', sa.String(length=200), nullable=True),
    sa.Column('inspector', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    sa.UniqueConstraint('path_inference_dent'),
    sa.UniqueConstraint('path_inference_scratch'),
    sa.UniqueConstraint('path_inference_spacing'),
    sa.UniqueConstraint('path_inspect_dent'),
    sa.UniqueConstraint('path_inspect_scratch'),
    sa.UniqueConstraint('path_inspect_spacing')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    op.drop_table('event')
    op.drop_table('user')
    op.drop_table('car')
    # ### end Alembic commands ###
