"""empty message

Revision ID: 58bf81be8803
Revises: 6c9de0753f40
Create Date: 2022-05-18 11:40:59.034380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58bf81be8803'
down_revision = '6c9de0753f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('is_damaged',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('is_damaged',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
