"""empty message

Revision ID: 6c9de0753f40
Revises: 3b8a2b517dac
Create Date: 2022-05-17 13:36:59.585289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9de0753f40'
down_revision = '3b8a2b517dac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('is_inferenced', sa.Boolean(), nullable=False),
    sa.Column('inferenced_on', sa.DateTime(), nullable=True),
    sa.Column('path_inference_dent', sa.String(length=100), nullable=False),
    sa.Column('path_inference_scratch', sa.String(length=100), nullable=False),
    sa.Column('path_inference_spacing', sa.String(length=100), nullable=False),
    sa.Column('is_inspected', sa.Boolean(), nullable=False),
    sa.Column('inspected_on', sa.DateTime(), nullable=True),
    sa.Column('path_inspect_dent', sa.String(length=100), nullable=True),
    sa.Column('path_inspect_scratch', sa.String(length=100), nullable=True),
    sa.Column('path_inspect_spacing', sa.String(length=100), nullable=True),
    sa.Column('inspector', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name=op.f('fk_entry_event_id_event'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entry')),
    sa.UniqueConstraint('event_id', name=op.f('uq_entry_event_id')),
    sa.UniqueConstraint('path_inference_dent', name=op.f('uq_entry_path_inference_dent')),
    sa.UniqueConstraint('path_inference_scratch', name=op.f('uq_entry_path_inference_scratch')),
    sa.UniqueConstraint('path_inference_spacing', name=op.f('uq_entry_path_inference_spacing')),
    sa.UniqueConstraint('path_inspect_dent', name=op.f('uq_entry_path_inspect_dent')),
    sa.UniqueConstraint('path_inspect_scratch', name=op.f('uq_entry_path_inspect_scratch')),
    sa.UniqueConstraint('path_inspect_spacing', name=op.f('uq_entry_path_inspect_spacing'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entry')
    # ### end Alembic commands ###
