"""empty message

Revision ID: 702184062644
Revises: 
Create Date: 2022-05-08 13:19:36.788103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '702184062644'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(length=10), nullable=False),
    sa.Column('registered_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
